export interface Program {
  id: string;
  name: string;
  duration: string;
  level: "undergraduate" | "postgraduate" | "phd" | "certificate" | "distance";
  campus: "global" | "prashanti";
  discipline: string;
  course: string;
  href: string;
}

export const programs: Program[] = [
  // UNDERGRADUATE — Global City Campus
  {
    id: "bca-cyber",
    name: "BCA Cybersecurity, Ethical Hacking and Digital Forensics",
    duration: "3 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "BCA",
    href: "/bca-cybersecurity-ethical-hacking-digital-forensics",
  },
  {
    id: "bca-ai-cloud",
    name: "BCA Artificial Intelligence, Cloud Computing and DevOps",
    duration: "3 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "BCA",
    href: "/bca-artificial-intelligence-cloud-computing-devops",
  },
  {
    id: "bba-sports",
    name: "BBA in Sports Management",
    duration: "3 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Management & Finance",
    course: "BBA",
    href: "/bba-in-sports-management",
  },
  {
    id: "bba-aviation",
    name: "BBA Aviation, Logistics and Supply Chain Management",
    duration: "3 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Management & Finance",
    course: "BBA",
    href: "/bba-logistics-and-aviation",
  },
  {
    id: "bba-intl",
    name: "BBA International Business, Digital Marketing and Business Analytics",
    duration: "3 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Management & Finance",
    course: "BBA",
    href: "/bba-business-management-digital-marketing-business-analytics",
  },
  {
    id: "bsc-cs",
    name: "B.Sc. Computer Science (Data Science)",
    duration: "3 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Science",
    course: "B.SC.",
    href: "/bsc-computer-science",
  },
  {
    id: "bcom-acca",
    name: "B.Com International Accounting & Finance integrated with ACCA",
    duration: "3 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Management & Finance",
    course: "BCOM",
    href: "/b-com-international-accounting-finance-integrated-with-acca",
  },
  {
    id: "btech-cse",
    name: "B.Tech. Computer Science and Engineering",
    duration: "4 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "B.TECH.",
    href: "/btech-computer-science-and-engineering",
  },
  {
    id: "btech-cse-le",
    name: "B.Tech. Computer Science and Engineering (Lateral Entry)",
    duration: "4 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Computer Science and IT (Lateral Entry)",
    course: "B.TECH.",
    href: "/btech-computer-science-and-engineering",
  },
  {
    id: "btech-aiml-le",
    name: "B.Tech. Computer Science (AI & ML) (Lateral Entry)",
    duration: "4 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Computer Science and IT (Lateral Entry)",
    course: "B.TECH.",
    href: "/btech-artificial-intelligence-machine-learning",
  },
  {
    id: "btech-ds-le",
    name: "B.Tech. Computer Science & Engineering (Data Science) (Lateral Entry)",
    duration: "4 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Computer Science and IT (Lateral Entry)",
    course: "B.TECH.",
    href: "/btech-computer-science-engineering-data-science",
  },
  {
    id: "btech-csit",
    name: "B.Tech. Computer Science and Information Technology",
    duration: "4 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "B.TECH.",
    href: "/btech-computer-science-and-information-technology",
  },
  {
    id: "btech-se",
    name: "B.Tech. Computer Science (Software Engineering)",
    duration: "4 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "B.TECH.",
    href: "/btech-computer-science-software-engineering",
  },
  {
    id: "btech-aiml",
    name: "B.Tech. Computer Science (Artificial Intelligence & Machine Learning)",
    duration: "4 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "B.TECH.",
    href: "/btech-artificial-intelligence-machine-learning",
  },
  {
    id: "btech-ds",
    name: "B.Tech. Computer Science & Engineering (Data Science)",
    duration: "4 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "B.TECH.",
    href: "/btech-computer-science-engineering-data-science",
  },
  {
    id: "btech-cyber",
    name: "B.Tech. Computer Science & Engineering (Cyber Security)",
    duration: "4 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "B.TECH.",
    href: "/btech-computer-science-engineering-cyber-security",
  },
  {
    id: "bot",
    name: "Bachelor of Occupational Therapy",
    duration: "4.5 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Allied and Healthcare Professions",
    course: "BOT",
    href: "/bachelor-of-occupational-therapy",
  },
  {
    id: "bsc-clinical-psych",
    name: "Bachelor of Science (B.Sc) in Clinical Psychology",
    duration: "3 Years",
    level: "undergraduate",
    campus: "global",
    discipline: "Clinical Psychology",
    course: "B.SC.",
    href: "/bsc-clinical-psychology",
  },

  // POSTGRADUATE — Global City Campus
  {
    id: "mca-cloud",
    name: "MCA Cloud Computing and DevOps",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "MCA",
    href: "/mca-cloud-computing-devops",
  },
  {
    id: "mca-cyber",
    name: "MCA Cybersecurity, Ethical Hacking and Cyber Forensics",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "MCA",
    href: "/mca-cybersecurity-ethical-hacking-cyber-forensics",
  },
  {
    id: "mca-aiml",
    name: "MCA Artificial Intelligence, Machine Learning and Data Science",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "MCA",
    href: "/mca-artificial-intelligence-machine-learning-data-science",
  },
  {
    id: "mca-ds",
    name: "MCA Data Science",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "MCA",
    href: "/mca-data-science",
  },
  {
    id: "mba-dual",
    name: "MBA Dual Specialisation",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Management & Finance",
    course: "MBA",
    href: "/mba-dual-specialisation",
  },
  {
    id: "mba-marketing",
    name: "MBA PRO Marketing, Finance and Business Analytics",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Management & Finance",
    course: "MBA",
    href: "/mba-marketing-finance-business-analytics",
  },
  {
    id: "mba-hospital",
    name: "MBA PRO Hospital Administration with Medical Tourism",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Management & Finance",
    course: "MBA",
    href: "/mba-hospital-administration-with-medical-tourism",
  },
  {
    id: "mba-logistics",
    name: "MBA PRO Logistics and Supply Chain Management",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Management & Finance",
    course: "MBA",
    href: "/mba-logistics-and-supply-chain-management",
  },
  {
    id: "mba-digital",
    name: "MBA PRO Digital Business Management and Data Analytics",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Management & Finance",
    course: "MBA",
    href: "/mba-digital-business-management-data-analytics",
  },
  {
    id: "mba-ai",
    name: "MBA PRO AI and Data Analytics",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Management & Finance",
    course: "MBA",
    href: "/mba-pro-ai-data-analytics",
  },
  {
    id: "mba-dm",
    name: "MBA in Digital Marketing and AI",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Management & Finance",
    course: "MBA",
    href: "/mba-digital-marketing-and-ai",
  },
  {
    id: "msc-cyber",
    name: "M.Sc. Cybersecurity, Ethical Hacking & Cyber Forensics",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "M.SC.",
    href: "/msc-cybersecurity-ethical-hacking-cyber-forensics",
  },
  {
    id: "msc-ds",
    name: "M.Sc. Data Science",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Science",
    course: "M.SC.",
    href: "/msc-data-science",
  },
  {
    id: "msc-clinical",
    name: "M.Sc (Clinical Psychology)",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Clinical Psychology",
    course: "M.SC.",
    href: "/msc-clinical-psychology",
  },
  {
    id: "msc-neuro",
    name: "M.Sc (Neuro Psychology)",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Clinical Psychology",
    course: "M.SC.",
    href: "/msc-neuropsychology",
  },
  {
    id: "msc-counselling",
    name: "M.Sc (Counselling Psychology)",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Clinical Psychology",
    course: "M.SC.",
    href: "/msc-counselling-psychology",
  },
  {
    id: "msc-health",
    name: "M.Sc (Health Psychology)",
    duration: "2 Years",
    level: "postgraduate",
    campus: "global",
    discipline: "Clinical Psychology",
    course: "M.SC.",
    href: "/msc-health-psychology",
  },

  // Ph.D — Global City Campus
  {
    id: "phd-cs",
    name: "Ph.D in Computer Science and Applications",
    duration: "3-5 Years",
    level: "phd",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "Ph.D",
    href: "/doctor-of-philosophy-in-computer-science",
  },
  {
    id: "phd-cse",
    name: "Ph.D in Computer Science and Engineering",
    duration: "3-5 Years",
    level: "phd",
    campus: "global",
    discipline: "Computer Science and IT",
    course: "Ph.D",
    href: "/doctor-of-philosophy-in-computer-science-and-engineering",
  },
  {
    id: "phd-mgmt",
    name: "Ph.D in Management and Commerce",
    duration: "3-5 Years",
    level: "phd",
    campus: "global",
    discipline: "Management & Finance",
    course: "Ph.D",
    href: "/doctor-of-philosophy-in-management-and-commerce",
  },
  {
    id: "phd-applied",
    name: "Ph.D in Applied Sciences",
    duration: "3-5 Years",
    level: "phd",
    campus: "global",
    discipline: "Science",
    course: "Ph.D",
    href: "/doctor-of-philosophy-in-applied-sciences",
  },
  {
    id: "phd-allied",
    name: "Ph.D in Allied and Healthcare Professions",
    duration: "3-5 Years",
    level: "phd",
    campus: "global",
    discipline: "Allied and Healthcare Professions",
    course: "Ph.D",
    href: "/doctor-of-philosophy-in-allied-sciences",
  },

  // UNDERGRADUATE — Prashanti Campus (Yoga)
  {
    id: "bpt",
    name: "Bachelor of Physiotherapy (BPT)",
    duration: "5 Years",
    level: "undergraduate",
    campus: "prashanti",
    discipline: "Allied and Healthcare Professions",
    course: "BPT",
    href: "/bachelor-of-physiotherapy",
  },
  {
    id: "yic",
    name: "Yoga Instructor Course",
    duration: "4 Weeks",
    level: "certificate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "YIC",
    href: "/yoga-instructor-course",
  },
  {
    id: "bsc-yoga-wellness",
    name: "B.Sc. in Yoga & Vedic Wellness",
    duration: "4 Years",
    level: "undergraduate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "B.SC.",
    href: "/bsc-yoga-vedic-therapy",
  },
  {
    id: "bsc-yoga-therapy",
    name: "B.Sc. in Yoga Therapy",
    duration: "4 Years",
    level: "undergraduate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "B.SC.",
    href: "/bachelor-of-science-in-yoga-therapy",
  },
  {
    id: "bsc-yoga-distance",
    name: "BSc Yoga (Distance Mode)",
    duration: "3 Years",
    level: "distance",
    campus: "prashanti",
    discipline: "Yoga",
    course: "B.SC.",
    href: "/bsc-yoga-vedic-therapy",
  },
  {
    id: "bnys",
    name: "Bachelor of Naturopathy and Yogic Sciences (BNYS)",
    duration: "5.5 Years",
    level: "undergraduate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "BNYS",
    href: "/bachelor-of-naturopathy-and-yogic-sciences",
  },

  // POSTGRADUATE — Prashanti Campus
  {
    id: "msc-yoga-therapy",
    name: "M.Sc. in Yoga Therapy",
    duration: "2 Years",
    level: "postgraduate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "M.SC.",
    href: "/master-of-science-in-yoga-therapy",
  },
  {
    id: "ma-yoga",
    name: "M.A. Yoga Darshanam",
    duration: "2 Years",
    level: "postgraduate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "M.A.",
    href: "/master-of-arts-in-yoga",
  },
  {
    id: "msc-yoga-wellness",
    name: "M.Sc. in Yoga & Vedic Wellness",
    duration: "2 Years",
    level: "postgraduate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "M.SC.",
    href: "/master-of-science-yoga-vedic-therapy",
  },
  {
    id: "msc-yoga-distance",
    name: "MSc Yoga (Distance Mode)",
    duration: "2 Years",
    level: "distance",
    campus: "prashanti",
    discipline: "Yoga",
    course: "M.SC.",
    href: "/master-of-science-in-yoga-therapy",
  },
  {
    id: "md-yoga",
    name: "MD Yoga",
    duration: "3 Years",
    level: "postgraduate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "MD",
    href: "/doctor-of-medicine-yoga",
  },

  // Ph.D / Certificates — Prashanti Campus
  {
    id: "phd-yoga",
    name: "Ph.D Yoga",
    duration: "3-5 Years",
    level: "phd",
    campus: "prashanti",
    discipline: "Yoga",
    course: "Ph.D",
    href: "/phd-yoga",
  },
  {
    id: "phd-naturopathy",
    name: "Ph.D Naturopathy",
    duration: "3-5 Years",
    level: "phd",
    campus: "prashanti",
    discipline: "Yoga",
    course: "Ph.D",
    href: "/phd-yoga",
  },
  {
    id: "phd-dance",
    name: "Ph.D Dance",
    duration: "3-5 Years",
    level: "phd",
    campus: "prashanti",
    discipline: "Yoga",
    course: "Ph.D",
    href: "/phd-yoga",
  },
  {
    id: "smet",
    name: "Self Management of Excessive Tension (SMET)",
    duration: "15 Days",
    level: "certificate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "SMET",
    href: "/self-management-of-excessive-tension",
  },
  {
    id: "ayurveda-lifestyle",
    name: "Ayurveda Lifestyle Management Course",
    duration: "1 Year",
    level: "certificate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "Certificate",
    href: "/ayurveda-lifestyle-management-course",
  },
  {
    id: "pdc",
    name: "Personality Development Camp",
    duration: "10 Days",
    level: "certificate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "Certificate",
    href: "/personality-development-camp",
  },
  {
    id: "pdc-children",
    name: "Personality Development Camp for Children",
    duration: "10 Days",
    level: "certificate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "Certificate",
    href: "/personality-development-camp-for-children",
  },
  {
    id: "hyo",
    name: "Himalaya Yoga Olympiad",
    duration: "Annual",
    level: "certificate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "Certificate",
    href: "/himalaya-yoga-olympiad",
  },
  {
    id: "yoga-humanities",
    name: "Division of Yoga & Humanities",
    duration: "15 Weeks",
    level: "certificate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "Certificate",
    href: "/division-of-yoga-and-humanities",
  },
  {
    id: "nr-yic",
    name: "Non-Residential YIC",
    duration: "3 Months",
    level: "certificate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "YIC",
    href: "/non-residential-yic",
  },
  {
    id: "anttc",
    name: "Ante Natal Teacher Training Certificate Course",
    duration: "60 Hours",
    level: "certificate",
    campus: "prashanti",
    discipline: "Yoga",
    course: "ANTTC",
    href: "/aerial-yoga-teacher-training-course",
  },
  {
    id: "dyt-distance",
    name: "DYT (Distance Mode)",
    duration: "1 Year",
    level: "distance",
    campus: "prashanti",
    discipline: "Yoga",
    course: "DYT",
    href: "/post-graduate-diploma-in-yoga-therapy",
  },
  {
    id: "yic-distance",
    name: "YIC (Distance Mode)",
    duration: "6 Months",
    level: "distance",
    campus: "prashanti",
    discipline: "Yoga",
    course: "YIC",
    href: "/yoga-instructor-course",
  },
];

export const filterOptions = {
  campus: [
    { id: "global", label: "Global Campus" },
    { id: "prashanti", label: "Prashanthi Kuteeram Campus" },
  ],
  level: [
    { id: "undergraduate", label: "Undergraduate" },
    { id: "postgraduate", label: "Postgraduate" },
    { id: "phd", label: "Ph.D" },
    { id: "distance", label: "Distance Learning" },
  ],
  discipline: [
    { id: "Management & Finance", label: "Management & Finance" },
    { id: "Science", label: "Science" },
    { id: "Computer Science and IT", label: "Computer Science and IT" },
    { id: "Computer Science and IT (Lateral Entry)", label: "Computer Science and IT (Lateral Entry)" },
    { id: "Yoga", label: "Yoga" },
    { id: "Allied and Healthcare Professions", label: "Allied and Healthcare Professions" },
    { id: "Clinical Psychology", label: "Clinical Psychology" },
  ],
  course: [
    { id: "BCA", label: "BCA" },
    { id: "BBA", label: "BBA" },
    { id: "BCOM", label: "BCOM" },
    { id: "B.SC.", label: "B.SC." },
    { id: "B.TECH.", label: "B.TECH." },
    { id: "MBA", label: "MBA" },
    { id: "M.SC.", label: "M.SC." },
    { id: "MCA", label: "MCA" },
    { id: "ANTTC", label: "ANTTC" },
  ],
};
