
-- Batch 4: MBA, M.Sc, Yoga, and remaining courses
UPDATE courses SET highlights = $j$[{"number":"01","icon":"briefcase","title":"Dual Specialization","description":"Two management specializations."},{"number":"02","icon":"bar-chart-3","title":"Analytics","description":"Business analytics skills."},{"number":"03","icon":"lotus","title":"Yoga Leadership","description":"Mindful management."}]$j$::jsonb, careers = $j$[{"icon":"briefcase","title":"Management Consultant","description":"Strategic consulting.","demand":"high"},{"icon":"building","title":"Business Manager","description":"General management.","demand":"high"},{"icon":"bar-chart-3","title":"Analytics Manager","description":"Data-driven decisions.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"Any Bachelor degree","minMarks":"","extras":["Any discipline accepted"],"quizQuestions":[{"question":"Have you completed a Bachelor degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹2,00,000"},{"year":"2nd Year","amount":"₹2,00,000"}]}$j$::jsonb WHERE slug = 'mba-dual-specialisation';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"trending-up","title":"Marketing & Finance","description":"Dual specialization."},{"number":"02","icon":"bar-chart-3","title":"Business Analytics","description":"Data-driven marketing."},{"number":"03","icon":"lotus","title":"Yoga Integration","description":"Mindful business."}]$j$::jsonb, careers = $j$[{"icon":"trending-up","title":"Marketing Manager","description":"Brand strategy.","demand":"high"},{"icon":"calculator","title":"Financial Analyst","description":"Financial planning.","demand":"high"},{"icon":"bar-chart-3","title":"Business Analyst","description":"Analytics.","demand":"high"}]$j$::jsonb, eligibility = $j${"primary":"Any Bachelor degree","minMarks":"","extras":["Any discipline"],"quizQuestions":[{"question":"Have you completed a Bachelor degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹2,00,000"},{"year":"2nd Year","amount":"₹2,00,000"}]}$j$::jsonb WHERE slug = 'mba-marketing-finance-business-analytics';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"building","title":"Hospital Management","description":"Healthcare administration."},{"number":"02","icon":"globe","title":"Medical Tourism","description":"Global health tourism."},{"number":"03","icon":"lotus","title":"Yoga & Wellness","description":"Integrative healthcare."}]$j$::jsonb, careers = $j$[{"icon":"building","title":"Hospital Admin","description":"Healthcare management.","demand":"high"},{"icon":"globe","title":"Medical Tourism Manager","description":"Health tourism.","demand":"growing"},{"icon":"heart","title":"Healthcare Consultant","description":"Advisory roles.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"Any Bachelor degree","minMarks":"","extras":["Any discipline"],"quizQuestions":[{"question":"Have you completed a Bachelor degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹2,00,000"},{"year":"2nd Year","amount":"₹2,00,000"}]}$j$::jsonb WHERE slug = 'mba-hospital-administration-medical-tourism';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"truck","title":"Supply Chain","description":"End-to-end logistics."},{"number":"02","icon":"building","title":"Management","description":"Business strategy."},{"number":"03","icon":"lotus","title":"Yoga","description":"Mindful leadership."}]$j$::jsonb, careers = $j$[{"icon":"truck","title":"Supply Chain Manager","description":"Logistics optimization.","demand":"high"},{"icon":"building","title":"Operations Director","description":"Operations strategy.","demand":"high"}]$j$::jsonb, eligibility = $j${"primary":"Any Bachelor degree","minMarks":"","extras":["Any discipline"],"quizQuestions":[{"question":"Have you completed a Bachelor degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹2,00,000"},{"year":"2nd Year","amount":"₹2,00,000"}]}$j$::jsonb WHERE slug = 'mba-logistics-supply-chain-management';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"globe","title":"Digital Business","description":"Digital transformation."},{"number":"02","icon":"bar-chart-3","title":"Data Analytics","description":"Business analytics."},{"number":"03","icon":"lotus","title":"Yoga","description":"Mindful innovation."}]$j$::jsonb, careers = $j$[{"icon":"globe","title":"Digital Manager","description":"Digital transformation.","demand":"high"},{"icon":"bar-chart-3","title":"Analytics Lead","description":"Data strategy.","demand":"high"}]$j$::jsonb, eligibility = $j${"primary":"Any Bachelor degree","minMarks":"","extras":["Any discipline"],"quizQuestions":[{"question":"Have you completed a Bachelor degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹2,00,000"},{"year":"2nd Year","amount":"₹2,00,000"}]}$j$::jsonb WHERE slug = 'mba-digital-business-management-data-analytics';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"brain","title":"AI for Business","description":"AI-powered management."},{"number":"02","icon":"bar-chart-3","title":"Data Analytics","description":"Advanced analytics."},{"number":"03","icon":"lotus","title":"Yoga Leadership","description":"Mindful management."}]$j$::jsonb, careers = $j$[{"icon":"brain","title":"AI Strategy Lead","description":"AI in business.","demand":"high"},{"icon":"bar-chart-3","title":"Analytics Director","description":"Data strategy.","demand":"high"}]$j$::jsonb, eligibility = $j${"primary":"Any Bachelor degree","minMarks":"","extras":["Work experience preferred"],"quizQuestions":[{"question":"Have you completed a Bachelor degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹2,50,000"},{"year":"2nd Year","amount":"₹2,50,000"}]}$j$::jsonb WHERE slug = 'mba-pro-ai-data-analytics';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"trending-up","title":"Digital Marketing","description":"Social media, SEO, SEM."},{"number":"02","icon":"brain","title":"AI Marketing","description":"AI-powered marketing tools."},{"number":"03","icon":"lotus","title":"Yoga","description":"Mindful creativity."}]$j$::jsonb, careers = $j$[{"icon":"trending-up","title":"Digital Marketing Head","description":"Marketing strategy.","demand":"high"},{"icon":"brain","title":"AI Marketing Specialist","description":"AI-driven campaigns.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"Any Bachelor degree","minMarks":"","extras":["Any discipline"],"quizQuestions":[{"question":"Have you completed a Bachelor degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹2,00,000"},{"year":"2nd Year","amount":"₹2,00,000"}]}$j$::jsonb WHERE slug = 'mba-digital-marketing-ai';

-- M.Sc courses
UPDATE courses SET highlights = $j$[{"number":"01","icon":"shield","title":"Advanced Security","description":"Security architecture."},{"number":"02","icon":"search","title":"Digital Forensics","description":"Forensic investigation."},{"number":"03","icon":"lotus","title":"Ethical Practice","description":"Yoga-based ethics."}]$j$::jsonb, careers = $j$[{"icon":"shield","title":"Security Researcher","description":"Security research.","demand":"high"},{"icon":"terminal","title":"Penetration Tester","description":"Security assessments.","demand":"high"},{"icon":"search","title":"Forensics Expert","description":"Digital forensics.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"B.Sc/BCA/B.Tech in CS or related","minMarks":"50%","extras":["Relevant bachelor degree"],"quizQuestions":[{"question":"Have you completed a relevant bachelor degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹1,50,000"},{"year":"2nd Year","amount":"₹1,50,000"}]}$j$::jsonb WHERE slug = 'msc-cybersecurity-ethical-hacking-cyber-forensics';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"bar-chart-3","title":"Statistical Theory","description":"Deep statistics."},{"number":"02","icon":"brain","title":"Advanced ML","description":"ML algorithms."},{"number":"03","icon":"lotus","title":"Analytical Clarity","description":"Yoga for clarity."}]$j$::jsonb, careers = $j$[{"icon":"bar-chart-3","title":"Senior Data Scientist","description":"Lead data projects.","demand":"high"},{"icon":"brain","title":"ML Research Scientist","description":"ML research.","demand":"growing"},{"icon":"briefcase","title":"Data Science Lead","description":"Lead teams.","demand":"high"}]$j$::jsonb, eligibility = $j${"primary":"B.Sc/BCA/B.Tech with relevant background","minMarks":"50%","extras":["Strong mathematics background"],"quizQuestions":[{"question":"Have you completed a relevant bachelor degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹1,50,000"},{"year":"2nd Year","amount":"₹1,50,000"}]}$j$::jsonb WHERE slug = 'msc-data-science';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"brain","title":"Clinical Assessment","description":"Psychological assessment."},{"number":"02","icon":"heart","title":"Psychotherapy","description":"Evidence-based therapy."},{"number":"03","icon":"lotus","title":"Yoga Therapy","description":"Yoga-psychology integration."}]$j$::jsonb, careers = $j$[{"icon":"brain","title":"Clinical Psychologist","description":"Clinical practice.","demand":"high"},{"icon":"heart","title":"Psychotherapist","description":"Therapeutic services.","demand":"high"},{"icon":"building","title":"Hospital Psychologist","description":"Healthcare settings.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"B.A./B.Sc. in Psychology","minMarks":"50%","extras":["Psychology degree required"],"quizQuestions":[{"question":"Have you completed Psychology undergrad?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹1,50,000"},{"year":"2nd Year","amount":"₹1,50,000"}]}$j$::jsonb WHERE slug = 'msc-clinical-psychology';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"brain","title":"Neuropsychological Assessment","description":"Cognitive testing."},{"number":"02","icon":"activity","title":"Brain-Behavior","description":"Neural cognition."},{"number":"03","icon":"lotus","title":"Yoga & Brain Health","description":"Yoga effects on cognition."}]$j$::jsonb, careers = $j$[{"icon":"brain","title":"Neuropsychologist","description":"Cognitive disorders.","demand":"high"},{"icon":"heart","title":"Rehabilitation Specialist","description":"Cognitive rehab.","demand":"growing"},{"icon":"microscope","title":"Neuroscience Researcher","description":"Brain research.","demand":"medium"}]$j$::jsonb, eligibility = $j${"primary":"B.A./B.Sc. in Psychology","minMarks":"50%","extras":["Psychology degree required"],"quizQuestions":[{"question":"Have you completed Psychology undergrad?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹1,50,000"},{"year":"2nd Year","amount":"₹1,50,000"}]}$j$::jsonb WHERE slug = 'msc-neuropsychology';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"heart","title":"Counseling","description":"Multiple therapeutic approaches."},{"number":"02","icon":"users","title":"Group Therapy","description":"Group counseling skills."},{"number":"03","icon":"lotus","title":"Yoga Counseling","description":"Integrative approaches."}]$j$::jsonb, careers = $j$[{"icon":"heart","title":"Counseling Psychologist","description":"Professional counseling.","demand":"high"},{"icon":"building","title":"School Counselor","description":"Educational settings.","demand":"high"},{"icon":"briefcase","title":"Corporate Counselor","description":"EAP services.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"B.A./B.Sc. in Psychology","minMarks":"50%","extras":["Psychology degree required"],"quizQuestions":[{"question":"Have you completed Psychology undergrad?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹1,50,000"},{"year":"2nd Year","amount":"₹1,50,000"}]}$j$::jsonb WHERE slug = 'msc-counselling-psychology';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"heart-pulse","title":"Health Behavior","description":"Psychology of health."},{"number":"02","icon":"activity","title":"Stress & Health","description":"Stress-illness relationships."},{"number":"03","icon":"lotus","title":"Yoga & Health","description":"Integrative health."}]$j$::jsonb, careers = $j$[{"icon":"heart","title":"Health Psychologist","description":"Health behavior.","demand":"growing"},{"icon":"building","title":"Wellness Director","description":"Wellness programs.","demand":"growing"},{"icon":"microscope","title":"Health Researcher","description":"Health research.","demand":"medium"}]$j$::jsonb, eligibility = $j${"primary":"B.A./B.Sc. in Psychology","minMarks":"50%","extras":["Psychology degree required"],"quizQuestions":[{"question":"Have you completed Psychology undergrad?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹1,50,000"},{"year":"2nd Year","amount":"₹1,50,000"}]}$j$::jsonb WHERE slug = 'msc-health-psychology';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"brain","title":"Advanced AI/ML","description":"Deep learning, NLP, computer vision."},{"number":"02","icon":"bar-chart-3","title":"Data Science","description":"Statistical analysis."},{"number":"03","icon":"lotus","title":"Yoga Integration","description":"Enhanced cognition."}]$j$::jsonb, careers = $j$[{"icon":"brain","title":"ML Engineer","description":"Production ML.","demand":"high"},{"icon":"bar-chart-3","title":"Data Scientist","description":"Advanced analytics.","demand":"high"},{"icon":"microscope","title":"AI Researcher","description":"AI research.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"Relevant Bachelor degree","minMarks":"50%","extras":["CS/Math/Stats background"],"quizQuestions":[{"question":"Have you completed a relevant bachelor degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹1,50,000"},{"year":"2nd Year","amount":"₹1,50,000"}]}$j$::jsonb WHERE slug = 'msc-artificial-intelligence-machine-learning-data-science';
