
-- Batch 5: Yoga, PhD, and remaining courses
UPDATE courses SET highlights = $j$[{"number":"01","icon":"lotus","title":"Yoga Therapy","description":"Evidence-based yoga therapy."},{"number":"02","icon":"book-open","title":"Vedic Studies","description":"Classical texts and philosophy."},{"number":"03","icon":"microscope","title":"Research","description":"Yoga research integration."}]$j$::jsonb, careers = $j$[{"icon":"lotus","title":"Yoga Therapist","description":"Clinical yoga therapy.","demand":"high"},{"icon":"building","title":"Wellness Director","description":"Wellness centers.","demand":"growing"},{"icon":"globe","title":"International Instructor","description":"Global teaching.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"10+2 or equivalent","minMarks":"","extras":["Any stream"],"quizQuestions":[{"question":"Have you completed 10+2?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹50,000"},{"year":"2nd Year","amount":"₹50,000"},{"year":"3rd Year","amount":"₹50,000"}]}$j$::jsonb WHERE slug = 'bsc-yoga-vedic-therapy';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"lotus","title":"Yoga Therapy","description":"Therapeutic yoga applications."},{"number":"02","icon":"heart","title":"Clinical Training","description":"Clinical yoga practice."},{"number":"03","icon":"microscope","title":"Research","description":"Evidence-based approach."}]$j$::jsonb, careers = $j$[{"icon":"lotus","title":"Yoga Therapist","description":"Clinical practice.","demand":"high"},{"icon":"heart","title":"Wellness Consultant","description":"Health consulting.","demand":"growing"},{"icon":"building","title":"Clinic Director","description":"Yoga clinic management.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"10+2 or equivalent","minMarks":"","extras":["Any stream"],"quizQuestions":[{"question":"Have you completed 10+2?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹50,000"},{"year":"2nd Year","amount":"₹50,000"},{"year":"3rd Year","amount":"₹50,000"}]}$j$::jsonb WHERE slug = 'bsc-yoga-therapy';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"lotus","title":"Advanced Yoga Therapy","description":"Advanced therapeutic techniques."},{"number":"02","icon":"microscope","title":"Research Methodology","description":"Yoga research skills."},{"number":"03","icon":"heart","title":"Clinical Practice","description":"Clinical applications."}]$j$::jsonb, careers = $j$[{"icon":"lotus","title":"Senior Yoga Therapist","description":"Advanced practice.","demand":"high"},{"icon":"microscope","title":"Yoga Researcher","description":"Research career.","demand":"growing"},{"icon":"building","title":"Program Director","description":"Therapy programs.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"B.Sc Yoga/BNYS or equivalent","minMarks":"50%","extras":["Relevant undergraduate degree"],"quizQuestions":[{"question":"Do you have a relevant undergraduate degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹75,000"},{"year":"2nd Year","amount":"₹75,000"}]}$j$::jsonb WHERE slug = 'msc-yoga-therapy';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"lotus","title":"Vedic Therapy","description":"Advanced Vedic healing."},{"number":"02","icon":"book-open","title":"Classical Texts","description":"Patanjali, Upanishads."},{"number":"03","icon":"microscope","title":"Research","description":"Vedic therapy research."}]$j$::jsonb, careers = $j$[{"icon":"lotus","title":"Vedic Therapist","description":"Traditional healing.","demand":"growing"},{"icon":"book-open","title":"Yoga Scholar","description":"Academic career.","demand":"medium"},{"icon":"globe","title":"International Teacher","description":"Global teaching.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"B.Sc Yoga or equivalent","minMarks":"50%","extras":["Yoga undergraduate degree"],"quizQuestions":[{"question":"Do you have a yoga-related undergraduate degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹75,000"},{"year":"2nd Year","amount":"₹75,000"}]}$j$::jsonb WHERE slug = 'msc-yoga-vedic-therapy';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"heart","title":"Naturopathy","description":"Natural healing methods."},{"number":"02","icon":"lotus","title":"Yogic Sciences","description":"Yoga therapy."},{"number":"03","icon":"activity","title":"Clinical Training","description":"Hospital training."}]$j$::jsonb, careers = $j$[{"icon":"heart","title":"Naturopath","description":"Natural medicine practice.","demand":"growing"},{"icon":"lotus","title":"Yoga Physician","description":"Yoga-based treatment.","demand":"growing"},{"icon":"building","title":"Hospital Doctor","description":"BNYS doctor.","demand":"high"}]$j$::jsonb, eligibility = $j${"primary":"10+2 with PCB","minMarks":"50%","extras":["Physics, Chemistry, Biology required"],"quizQuestions":[{"question":"Have you completed 10+2 with PCB?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹1,50,000"},{"year":"2nd Year","amount":"₹1,50,000"},{"year":"3rd Year","amount":"₹1,50,000"},{"year":"4th Year","amount":"₹1,50,000"},{"year":"5th Year (Internship)","amount":"₹75,000"}]}$j$::jsonb WHERE slug = 'bachelor-of-naturopathy-yogic-sciences';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"microscope","title":"Research","description":"Advanced yoga research."},{"number":"02","icon":"lotus","title":"Clinical Yoga","description":"Yoga medicine."},{"number":"03","icon":"book-open","title":"Specialization","description":"Deep specialization."}]$j$::jsonb, careers = $j$[{"icon":"microscope","title":"Yoga Researcher","description":"Academic research.","demand":"growing"},{"icon":"lotus","title":"Yoga Medicine Specialist","description":"Clinical practice.","demand":"growing"},{"icon":"building","title":"Academic","description":"Teaching and research.","demand":"medium"}]$j$::jsonb, eligibility = $j${"primary":"BNYS/MD Yoga or equivalent","minMarks":"55%","extras":["Medical/yoga postgraduate degree"],"quizQuestions":[{"question":"Do you have a relevant postgraduate degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹1,50,000"},{"year":"2nd Year","amount":"₹1,50,000"},{"year":"3rd Year","amount":"₹1,50,000"}]}$j$::jsonb WHERE slug = 'doctor-of-medicine-yoga';

-- Certificate/Diploma courses
UPDATE courses SET highlights = $j$[{"number":"01","icon":"lotus","title":"PG Diploma","description":"Postgraduate yoga therapy."},{"number":"02","icon":"heart","title":"Clinical Skills","description":"Therapeutic applications."},{"number":"03","icon":"award","title":"Certification","description":"PG Diploma certificate."}]$j$::jsonb, careers = $j$[{"icon":"lotus","title":"Yoga Therapist","description":"Clinical practice.","demand":"high"},{"icon":"building","title":"Wellness Center","description":"Wellness roles.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"Bachelor degree in any discipline","minMarks":"","extras":["Any bachelor degree"],"quizQuestions":[{"question":"Have you completed a Bachelor degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹10,000 (Non-Refundable)","yearlyFees":[{"year":"Full Program","amount":"₹50,000"}]}$j$::jsonb WHERE slug = 'pg-diploma-yoga-therapy';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"lotus","title":"Yoga for Doctors","description":"Medical yoga applications."},{"number":"02","icon":"heart","title":"Integrative Medicine","description":"Yoga + modern medicine."},{"number":"03","icon":"award","title":"Certification","description":"PG Diploma for MDs."}]$j$::jsonb, careers = $j$[{"icon":"heart","title":"Integrative Doctor","description":"Yoga + medicine.","demand":"growing"},{"icon":"lotus","title":"Medical Yoga Expert","description":"Hospital yoga.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"MBBS/BAMS/BHMS or equivalent","minMarks":"","extras":["Medical degree required"],"quizQuestions":[{"question":"Do you have a medical degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹10,000 (Non-Refundable)","yearlyFees":[{"year":"Full Program","amount":"₹75,000"}]}$j$::jsonb WHERE slug = 'pg-diploma-yoga-for-doctors';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"lotus","title":"YIC Training","description":"Comprehensive yoga instructor course."},{"number":"02","icon":"presentation","title":"Teaching Methods","description":"Effective yoga teaching."},{"number":"03","icon":"award","title":"Certification","description":"Internationally recognized YIC."}]$j$::jsonb, careers = $j$[{"icon":"lotus","title":"Yoga Instructor","description":"Professional yoga teaching.","demand":"high"},{"icon":"building","title":"Studio Teacher","description":"Yoga studio roles.","demand":"high"},{"icon":"globe","title":"International Teacher","description":"Global opportunities.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"10+2 or equivalent","minMarks":"","extras":["Age 18+","Physical fitness"],"quizQuestions":[{"question":"Have you completed 10+2?","yesIsCorrect":true},{"question":"Are you 18 or older?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹5,000 (Non-Refundable)","yearlyFees":[{"year":"Full Program","amount":"₹30,000"}]}$j$::jsonb WHERE slug = 'yoga-instructor-course';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"calendar","title":"Weekend Format","description":"Learn while working."},{"number":"02","icon":"lotus","title":"Full Curriculum","description":"Complete YIC training."},{"number":"03","icon":"award","title":"Certification","description":"Same YIC certificate."}]$j$::jsonb, careers = $j$[{"icon":"lotus","title":"Part-Time Yoga Teacher","description":"Teach alongside career.","demand":"high"},{"icon":"building","title":"Studio Instructor","description":"Weekend classes.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"10+2 or equivalent","minMarks":"","extras":["Bengaluru residents preferred"],"quizQuestions":[{"question":"Have you completed 10+2?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹5,000 (Non-Refundable)","yearlyFees":[{"year":"Full Program","amount":"₹25,000"}]}$j$::jsonb WHERE slug = 'non-residential-yic';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"brain","title":"Stress Science","description":"Understand stress mechanisms."},{"number":"02","icon":"lotus","title":"Yoga Practices","description":"Simple effective techniques."},{"number":"03","icon":"heart","title":"Emotional Balance","description":"Manage emotions."}]$j$::jsonb, careers = $j$[{"icon":"heart","title":"Personal Wellness","description":"Lifelong stress management.","demand":"high"},{"icon":"users","title":"Workshop Facilitator","description":"Conduct SMET workshops.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"Anyone 18+ years","minMarks":"","extras":["Open to all"],"quizQuestions":[{"question":"Are you 18 or older?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹1,000 (Non-Refundable)","yearlyFees":[{"year":"Full Program","amount":"₹3,000"}]}$j$::jsonb WHERE slug = 'self-management-excessive-tension';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"leaf","title":"Ayurvedic Principles","description":"Foundational concepts."},{"number":"02","icon":"heart","title":"Diet & Nutrition","description":"Constitution-based nutrition."},{"number":"03","icon":"lotus","title":"Yoga Integration","description":"Ayurveda-yoga synergy."}]$j$::jsonb, careers = $j$[{"icon":"leaf","title":"Ayurveda Consultant","description":"Lifestyle consultation.","demand":"growing"},{"icon":"heart","title":"Wellness Advisor","description":"Health coaching.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"Anyone 18+ years","minMarks":"","extras":["Open to all"],"quizQuestions":[{"question":"Are you 18 or older?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹5,000 (Non-Refundable)","yearlyFees":[{"year":"Full Program","amount":"₹25,000"}]}$j$::jsonb WHERE slug = 'ayurveda-lifestyle-management';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"wind","title":"Aerial Techniques","description":"Hammock yoga mastery."},{"number":"02","icon":"shield","title":"Safety Protocols","description":"Essential safety training."},{"number":"03","icon":"award","title":"Certification","description":"Aerial yoga certification."}]$j$::jsonb, careers = $j$[{"icon":"wind","title":"Aerial Yoga Instructor","description":"Teach aerial yoga.","demand":"growing"},{"icon":"building","title":"Studio Teacher","description":"Yoga studios.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"Prior yoga teaching experience or YIC","minMarks":"","extras":["Physical fitness required"],"quizQuestions":[{"question":"Do you have yoga teaching experience?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹5,000 (Non-Refundable)","yearlyFees":[{"year":"Full Program","amount":"₹40,000"}]}$j$::jsonb WHERE slug = 'aerial-yoga-teacher-training';

-- PhD courses
UPDATE courses SET highlights = $j$[{"number":"01","icon":"microscope","title":"Research Focus","description":"Deep research in chosen area."},{"number":"02","icon":"book-open","title":"Publications","description":"Publish in peer-reviewed journals."},{"number":"03","icon":"lotus","title":"Yoga Integration","description":"Unique research environment."}]$j$::jsonb, careers = $j$[{"icon":"microscope","title":"Research Scientist","description":"Academic research.","demand":"medium"},{"icon":"building","title":"Professor","description":"Academic career.","demand":"medium"},{"icon":"briefcase","title":"Industry Researcher","description":"R&D roles.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"Relevant Master degree","minMarks":"55%","extras":["Master degree in relevant field"],"quizQuestions":[{"question":"Do you have a relevant Master degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"Per Year","amount":"₹1,00,000"}]}$j$::jsonb WHERE slug IN ('phd-computer-science','phd-computer-science-engineering','phd-commerce-management','phd-applied-sciences','phd-allied-sciences','phd-english','phd-yoga');

-- Remaining courses
UPDATE courses SET highlights = $j$[{"number":"01","icon":"book-open","title":"Classical Texts","description":"Yoga Sutras, Gita, Upanishads."},{"number":"02","icon":"lotus","title":"Practice","description":"Philosophy in practice."},{"number":"03","icon":"microscope","title":"Research","description":"Philosophical research."}]$j$::jsonb, careers = $j$[{"icon":"book-open","title":"Yoga Scholar","description":"Academic research.","demand":"medium"},{"icon":"presentation","title":"Philosophy Teacher","description":"Teach yoga philosophy.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"Bachelor degree in any discipline","minMarks":"","extras":["Interest in philosophy"],"quizQuestions":[{"question":"Have you completed a Bachelor degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹75,000"},{"year":"2nd Year","amount":"₹75,000"}]}$j$::jsonb WHERE slug = 'master-of-arts-yoga-darshanam';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"heart","title":"Physiotherapy","description":"Rehabilitation science."},{"number":"02","icon":"activity","title":"Clinical Training","description":"Hospital practice."},{"number":"03","icon":"lotus","title":"Yoga Integration","description":"Yoga + physiotherapy."}]$j$::jsonb, careers = $j$[{"icon":"heart","title":"Physiotherapist","description":"Clinical practice.","demand":"high"},{"icon":"building","title":"Hospital Physio","description":"Hospital roles.","demand":"high"},{"icon":"trophy","title":"Sports Physio","description":"Sports rehabilitation.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"10+2 with PCB","minMarks":"50%","extras":["Physics, Chemistry, Biology required"],"quizQuestions":[{"question":"Have you completed 10+2 with PCB?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹2,00,000"},{"year":"2nd Year","amount":"₹2,00,000"},{"year":"3rd Year","amount":"₹2,00,000"},{"year":"4th Year","amount":"₹2,00,000"}]}$j$::jsonb WHERE slug = 'bachelor-of-physiotherapy';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"hand","title":"Occupational Therapy","description":"Rehabilitation skills."},{"number":"02","icon":"heart","title":"Clinical Training","description":"Hospital practice."},{"number":"03","icon":"lotus","title":"Yoga Integration","description":"Holistic rehabilitation."}]$j$::jsonb, careers = $j$[{"icon":"hand","title":"Occupational Therapist","description":"Rehabilitation practice.","demand":"high"},{"icon":"building","title":"Hospital OT","description":"Healthcare settings.","demand":"high"},{"icon":"users","title":"Pediatric OT","description":"Children therapy.","demand":"growing"}]$j$::jsonb, eligibility = $j${"primary":"10+2 with PCB","minMarks":"50%","extras":["Physics, Chemistry, Biology required"],"quizQuestions":[{"question":"Have you completed 10+2 with PCB?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹25,000 (Non-Refundable)","yearlyFees":[{"year":"1st Year","amount":"₹2,00,000"},{"year":"2nd Year","amount":"₹2,00,000"},{"year":"3rd Year","amount":"₹2,00,000"},{"year":"4th Year","amount":"₹2,00,000"}]}$j$::jsonb WHERE slug = 'bachelor-of-occupational-therapy';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"award","title":"Highest Degree","description":"D.Sc./D.Litt. recognition."},{"number":"02","icon":"microscope","title":"Research Excellence","description":"Lifetime research."},{"number":"03","icon":"globe","title":"Global Recognition","description":"International prestige."}]$j$::jsonb, careers = $j$[{"icon":"award","title":"Distinguished Professor","description":"Senior academic roles.","demand":"medium"},{"icon":"microscope","title":"Research Director","description":"Lead research institutions.","demand":"medium"}]$j$::jsonb, eligibility = $j${"primary":"Ph.D. with significant research contribution","minMarks":"","extras":["10+ years post-PhD research"],"quizQuestions":[{"question":"Do you have a Ph.D. degree?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹50,000 (Non-Refundable)","yearlyFees":[{"year":"Evaluation Fee","amount":"₹2,00,000"}]}$j$::jsonb WHERE slug = 'dsc-dlitt';

UPDATE courses SET highlights = $j$[{"number":"01","icon":"palette","title":"Arts Integration","description":"Yoga and creative arts."},{"number":"02","icon":"globe","title":"Global Perspectives","description":"International yoga studies."},{"number":"03","icon":"lotus","title":"Practice","description":"Grounded in yoga."}]$j$::jsonb, careers = $j$[{"icon":"palette","title":"Yoga Arts","description":"Creative expression.","demand":"growing"},{"icon":"book-open","title":"Researcher","description":"Yoga culture research.","demand":"medium"}]$j$::jsonb, eligibility = $j${"primary":"Varies by program","minMarks":"","extras":["Contact division for requirements"],"quizQuestions":[{"question":"Are you interested in yoga humanities?","yesIsCorrect":true}]}$j$::jsonb, fee = $j${"registration":"₹10,000 (Non-Refundable)","yearlyFees":[{"year":"Per Semester","amount":"₹50,000"}]}$j$::jsonb WHERE slug = 'division-yoga-humanities';
